### PR TITLE
BUG: Only set _DEBUG flag if _DEBUG flag was originally defined

### LINKED ISSUE #1: Build fails due to re-adding _DEBUG even in Release builds
Workaround for using Release python with Debug OpenCV causes conflicts when using Release OpenCV

### PR DESCRIPTION
**Pull request by adamrankin**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution :+1: 

Is this change backported from upstream ? If yes, what was the associated commit ?

**Comment by adamrankin** [comment]
No, this is my fix.

**Comment by jcfr** [comment]
Thanks for clarifying. Should a PR be open upstream ? Or is the problem specific to your setup ?

**Comment by adamrankin** [comment]
No, this is specific to Slicer using OpenCV.

**Pull request merged**
